### ISSUE TITLE
move sfy-data to kubernetes (or something)

### ISSUE THREAD

**Issue by gauteh** [gauteh/sfy#118]
With #114 it is possible to set up sfy-data with postgres and kubernets. we're hitting some limits w.r.t scaling and backup of disk-space. the server is stateless so it is possible to have multiple servers. @cskarby started the process of setting this up, and I have also not had any time to follow up yet. @jerabaul29 do you have anything to do with kubernetes?

**Comment by jerabaul29** [comment]
I am involved a bit in a project that uses k8s on Azure. I am by no way an expert, but would be interested to learn more. Not sure with what hours / when I could find the time though (but that could be a side project for the summer or something like this).

**Comment by jerabaul29** [comment]
(I will try to discuss this next time I have a planning meeting, I would really be interested to look a bit deeper into this, would be really great for me to learn more about these technologies :) ) .

**Comment by gauteh** [comment]
Sounds good!
