### ISSUE TITLE
Is it possible to get full GPS information at "high" frequency from the build in GPS of the modem?

### ISSUE THREAD

**Issue by jerabaul29** [gauteh/sfy#29]
From our discussion of today; would be possibly useful for generating test data for designing / testing custom 6dof + GPS Kalman filters:

- is it possible to get lat, lon, timestamp, velocity, heading, quality indications from the GPS (are there even more quantities we may be interesed in?)
- at as high frequency as possible; what kind of frequency is possible with the GPS on the modem? 1hz, 2.5hz, 5hz, 10hz, 25hz, 50hz are common values

**Comment by gauteh** [comment]
Velocity and sensitivity is available

**Comment by jerabaul29** [comment]
yippi :) .

**Comment by jerabaul29** [comment]
We should try to get the GPS datasheet (exact GPS chip?) to be able to check specs.

May want to use for "true real value" a GPS RTK "in addition" if possible, if close to the coast, and RTK signal is available, accuracy is around 1cm.

**Comment by jerabaul29** [comment]
(with RTK 1cm is absolute accuracy, wonder if relative accuracy may be even higher (since normal gps has typically 2.5-5m absolute accuracy, but relative accuracy may already there be much better).

**Comment by jerabaul29** [comment]
Another way to test against ground truth is to use a wheel like Jim et co, but dataset of field data would still be useful anyways:)
