### ISSUE TITLE
data about pololu

### ISSUE THREAD

**Issue by jerabaul29** [gauteh/sfy#34]
I was browsing around, just FYI regarding this page: https://github.com/gauteh/sfy/blob/main/hardware/Hardware.md pololu does not have a github repo, but they do have some resource files (drawings dimentions etc):

https://www.pololu.com/product/2122/resources

for example: https://a.pololu-files.com/picture/0J5668.1200.png?580ff655e55f0f82ebededac2616f780 .

**Comment by gauteh** [comment]
Thanks, that is useful if we want to create a PCB.
