### ISSUE TITLE
IMU: use continuous FIFO mode, not FIFO mode

### ISSUE THREAD

**Issue by gauteh** [gauteh/sfy#35]

**Comment by jerabaul29** [comment]
what is the difference? :)

**Comment by gauteh** [comment]
Minor difference, ST suggested I do this. I don't think there is a
difference now, but it should be in continuous mode for what I am trying to
do. Otherwise the FIFO needs to be reset every time I drain it. But then I
would loose a few samples.

fre. 25. feb. 2022, 20:53 skrev JR ***@***.***>:

**Comment by gauteh** [comment]
Its fine to use it as it is: https://community.st.com/s/case/5003W00000FWwfEQAT

**Comment by jerabaul29** [comment]
Linken funker ikke, har du en annen link / navn på selve tråd så at jeg kan søke den? :) .

**Comment by gauteh** [comment]
Må kanskje være logga inn med min konto:

[Case 00152476.pdf](https://github.com/gauteh/sfy/files/8161418/Case.00152476.pdf)

**Comment by jerabaul29** [comment]
Jeg har registrert meg, og er logga på. Rart. Men takk :) .
