### ISSUE TITLE
Antennas - Norway LTE Frequencies

### ISSUE THREAD

**Issue by BenoitLD** [gauteh/sfy#49]
FDD/

01/ IMT 2100 MHz
03/ DCS 1800 MHz
07/ IMT-E 2600 MHz
08/ E-GSM 900 MHz
20/ EUDD 800 MHz
28/ APT 700 MHz
31/ NMT 450 MHz
65/ E-IMT 2100 MHz (??)

TDD/

38/ IMT-E 2600 MHz

**Comment by gauteh** [comment]
Thanks, does this also include GSM bands used in Norway?
