### ISSUE TITLE
Need more components

### ISSUE THREAD

**Issue by BenoitLD** [gauteh/sfy#51]
We need:

* Thick black wire (~ 2.5 mm diameter) for the buoys.
* Connectors
* Adapter for antenna: @BenoitLD which?

**Comment by jerabaul29** [comment]
I have been using down to gauge 16 if I remember well; that reduces a lot the voltage drops, no doubt there, but it is also quite a bit less convenient to solder - taking all the threads of the cable, one usually do not get space for them all in the typical "through holes" on PCBs.

**Comment by gauteh** [comment]
Yes, as long as we keep the wires short it shouldn't be a problem. After starting to power the rest of the system from the notecard it shouldn't be a problem anymore anyway and the ground's should follow each other. Need some flexible (easily solderable) wire though for batterypacks, if you have suggestions for mouser / adafruit / sparkfun products please let me know.

**Comment by jerabaul29** [comment]
Mmh, not sure I have anything special to suggest - I have been using these, they are fine enough, but not sure if this is what you look for: https://www.elfadistrelec.no/en/stranded-wire-pvc-8mm-tinned-copper-black-3055-30-5m-alpha-wire-3055-bk005/p/30083071?trackQuery=18+awg+wire&pos=31&origPos=40&origPageSize=50&track=true .
