### ISSUE TITLE
SD-card can become ejected in current configuration

### ISSUE THREAD

**Issue by gauteh** [gauteh/sfy#61]
During sea-trials SD-card got ejected, no messages could be stored to SD, but they were still successfully transmitted over the cellular. Maybe you have some ideas @BenoitLD for how to secure the SD-card during deployment.

**Comment by jerabaul29** [comment]
Tough! I think some people 'heat gun glue' SD cards, but then of course harder to take out - maybe possible to read the SD card content through the Artemis instead of extracting the SD card, in which case it could be glued in position?

**Comment by gauteh** [comment]
Yeah! I was sure there was filesystem issues, so it was a good kind of surprise. Reading through something kind of defies the purpose of making it easy to read in a computer: I'm thinking maybe a thin zip-tie... ?

It is (already) possible to read the storage data over cellular, e.g. if buoy drifts off-shore and pops up again somewhere with network cover.

**Comment by gauteh** [comment]
Difficult if the buoy has been filled with water and the Artemis is a rusty
blob :D
