### ISSUE TITLE
dashboard: how often are the data retrieved?

### ISSUE THREAD

**Issue by jerabaul29** [gauteh/sfy#63]
Just being curious / as usual just brainstorming: how often are the data retrieved from the different sources? Looks like the NOFO-OPV data took a bit of time to update - is there an attempt to retrieve iridium and GSM data each time a connection is established (to make sure it is refreshed), or is it taking place at fixed time, or else? Would it be possible to have a "refresh all data sources" button to force a refresh? :)

**Comment by gauteh** [comment]
I would like to avoid being able to control the server using the read-token, so I think in the current design it shouldn't be possible to force a refresh from iridium - but there should be a mechanism for the web ui to update data from server without reloading the page.
