### ISSUE TITLE
PCB master-board for mounting components onto

### ISSUE THREAD

**Issue by gauteh** [gauteh/sfy#64]
* Should fit in 75mm bottle
* Can it be made circular to fit horizontally?

See corresponding issue in OpenMetBuoy:
* https://github.com/jerabaul29/tracker_and_waves_instrument/issues/151

Use e.g. JLCPCB for prototyping.

(@BenoitLD )

**Comment by jerabaul29** [comment]
A few small notes:

- I have used seeed studio for producing PCBs for this project: https://github.com/jerabaul29/LoggerWavesInIce_InSituWithIridium/tree/master/PCB_electronics/Logger_and_power_v1 . It was working well, very low cost, and actually reasonably fast - so may be an option. The nice thing with Seeed is that they are very "KiCAD-friendly", and they have a library of standard parts that they can very easily use to produce your design: https://www.seeedstudio.com/opl.html (components there are available as KiCAD components if I remember well)

- There is an additional PCB on the making from LabMaker Gmbh; I will send it to you in private email (not for diffusion without LabMaker green light :) ), may be a source of inspiration / tips and tricks too :) .
