### ISSUE TITLE
PCB-fixes for v0.3

### ISSUE THREAD

**Issue by gauteh** [gauteh/sfy#86]
- [x] 10kOhm pull-up on SD MISO
- [x] 10kOhm pull-up on SD MOSI
- [x] 10kOhm pull-up on SD CS (chip-select)
- [x] 10kOhm pull-up on SD CLK
- [x] 10kOhm on non-connected SD pins
- [x] approx 0.1 uF (tantalum?) capacitor on SD power-supply
- [x] 10 uF on SD power-supply
- [x] GND SD card house
- [x] Move card-holder?
- [x] Larger screw-holes
- [x] Larger +BATT / -BATT holes
- [x] Move switch-holes
- [x] Update version number on silk-screen
- [x] Add MET logo on silk-screen?

**Comment by gauteh** [comment]
![sd-pull-up](https://user-images.githubusercontent.com/56827/191972468-c7e84f5c-cc47-4d8d-b0b4-49511c9fc01f.jpg)

with pull-ups.

**Comment by jerabaul29** [comment]
Funker også SD kort med ekstra komponenter rundt? :)

**Comment by jerabaul29** [comment]
Det er bare brainstorming, og godt mulig du kan det mye bedre enn meg :) (hvis det, sorry for at jeg bare skriver åpenbare ting her ^^ ). Men angående SD-kort: det er ganske høy frekvens på de signalene som går gjennom SPI. Tror da at det kan vært viktig å gjøre sikker at:

- det er så korte PCB traces som mulig
- det er ikke noe "current loop", ie GND følger tett på +3.3V og signalene, og GND kommer tilbake gjennom spesifiske PCB traces som følger +3.3V og signalene, ikke gjennom en base plate som kan gi en ganske annerledes vei til tilbakestrøm
- CLK og DAT er nære hverandre

**Comment by gauteh** [comment]
Gode forslag, lurt å sjekke hvis vi rekker før vi bestiller neste. Funker
tilsynelatende bra med motstander.

fre. 23. sep. 2022, 16:07 skrev JR ***@***.***>:

**Comment by jerabaul29** [comment]
Aaah, så kult at det funker, gratulerer :) . Da funket alt på PCBen med et par ekstra komponenter stemmer det? :)

**Comment by gauteh** [comment]
Ja, litt ting som må gjerast meir praktisk som du ser. Men ellers ser det
bra ut!

fre. 23. sep. 2022, 16:24 skrev JR ***@***.***>:

**Comment by zerblatt007** [comment]
MET logo er vel smart? God plass der SD kortet stod?

**Comment by gauteh** [comment]
Blir det under notecarrieren? Sikkert ikkje so dumt med ein URL eller ein eller anna kontakt-info.

**Comment by gauteh** [comment]
La til ein MET logo og ein link, eg antar det hullet framfor SD-kortet er for å låse det? Ellers hadde det blitt litt meir plass.

**Comment by zerblatt007** [comment]
Har flyttet skruen litt, men logo og link ser jo gei ut, men er jeg.. :)

**Comment by zerblatt007** [comment]
Da er jeg vel så fornøyd jeg kan bli akkurat nå, tror jeg.
Labling var lurt for da ser man hva nettene heter i PCB mode, men jeg har ikke gjort det på alt.
NC greiene får jeg ikke til å fungere, så det gir jeg opp nå, men tror alt skal være koblet riktig.
Jeg la på en rev2022-09 tekst på baksiden som jeg tenkte kunne være lurt også. Hadde håpet på å kunne bruke en variabel i teksten, men fant ikke noe sånn fort, så jeg skrev det inn manuelt.

**Comment by gauteh** [comment]
Ja, dette ser bra ut. Da er vi vel i grunnen klar til å bestille ei ny runde? Kan la det ligge å surre litt til i kveld eller i morgon før eg gjer bestillinga i tilfelle vi tenker på noko.

**Comment by gauteh** [comment]
Da har eg bestilt eit nytt sett. Sidan vi kun har komponenter på ei side vart det noken hakk billigare. Det var minimal pris for å bestille fleire stk (0.20 USD per prett utover 5), so eg bestilte 15. Vart 79USD inkl assembly og frakt.

**Comment by jerabaul29** [comment]
Det blir spennende :) .

Ser litt på EasyEDA vs KiCAD, er litt i tvil: det er litt synd med noe close source nettbasert løsning, men jeg må si at det høres kjempefint ut å ha en CAD program som funker "out of the box" med "library parts" og kan bli brukt til å bestille med bare en click :) .

**Comment by gauteh** [comment]
Ja, det har sine bakdeler. Det er utrulig strømlinjeforma.. tar ti minutt til det er bestilt i frå eit ferdig PCB brett. Du kan eksportere til Altium og det finst konverter til kicad frå easyeda arkiv.
